# NumPy Library Features:
- Powerful library for numerical computing in Python, providing support for arrays, matrices, and many mathematical functions.
- Supports broadcasting, a method that allows numpy to work with arrays of different shapes for arithmetic operations.
- Offers a wide range of mathematical functions, including linear algebra, statistical operations, and more.
- Written in C, NumPy operations are extremely fast compared to Python lists, making it suitable for performance-critical applications.

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import seaborn as sns

In [4]:
np.arange(0,5,2)

array([0, 2, 4])

In [5]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand(4)

array([0.55901654, 0.24919086, 0.09401735, 0.68396424])

In [10]:
np.random.rand(3,3)

array([[0.65587848, 0.05464368, 0.29342164],
       [0.56939237, 0.47969604, 0.18269866],
       [0.78197258, 0.37337265, 0.0138548 ]])

In [11]:
#samples from normal/ gaussian distribution
np.random.randn(2)     #normal

array([-0.0470086 ,  2.03209009])

In [12]:
np.random.randint(0,100,5) #start,stop, no. of points

array([23, 16, 16, 58, 75])

In [13]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
ranarr = np.random.randint(0,50,10)        
ranarr

array([38, 35, 17, 32, 34, 12, 47, 31, 10, 16])

In [16]:
ranarr.min()  #min._value

10

In [17]:
ranarr.max()  #max_value

47

In [18]:
ranarr.argmax()   #max_value_position

6

In [19]:
ranarr.argmin()  #min_value_position

8

In [20]:
arr.shape

(25,)

In [21]:
a = np.arange(25)
b = a.reshape(5,5)
b.shape              #2-d matrix

(5, 5)

In [22]:
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In [23]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr[4]

4

In [25]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [26]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [27]:
slice = arr[5:8]
slice

array([5, 6, 7])

In [28]:
slice[:] = 99
slice

array([99, 99, 99])

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
mat[1:,2:]    #2-d slicing

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [31]:
mat[2,3]     #exact loc

14

In [32]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4, 99, 99, 99,  8,  9, 10])

In [33]:
arr>5
#bool_arr = arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [34]:
arr+arr
#other operations include:
#sub,mul,div,log,exp,pow,sin,max
#for more universal functions: docs.scipy.org/

array([  0,   2,   4,   6,   8, 198, 198, 198,  16,  18,  20])

In [35]:
sqrt = np.sqrt(arr)
sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       9.94987437, 9.94987437, 9.94987437, 2.82842712, 3.        ,
       3.16227766])